import {NextResponse} from "next/server";
import {z} from "zod";
import {resolveWorkspace,WorkspaceAccessError} from "@/lib/workspace/context";
import {addSuppressionPersistent,listSuppressionsPersistent,removeSuppressionPersistent} from "@/services/persistence/suppression";
import {recordAuditPersistent} from "@/services/persistence/operations";

const createSchema=z.object({type:z.enum(["email","phone","domain"]),value:z.string().trim().min(3).max(500),reason:z.string().trim().max(500).nullable().optional()});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const context=await resolveWorkspace(id);return NextResponse.json({workspaceId:context.workspaceId,mode:context.mode,entries:await listSuppressionsPersistent(context.workspaceId)});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});throw error;}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid suppression entry",issues:parsed.error.issues},{status:400});try{const context=await resolveWorkspace(id);const entry=await addSuppressionPersistent({workspaceId:context.workspaceId,...parsed.data});await recordAuditPersistent({workspaceId:context.workspaceId,action:"suppression.added",entityType:"suppression",entityId:entry.id,metadata:{type:entry.type}});return NextResponse.json({entry,mode:context.mode},{status:201});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});return NextResponse.json({error:error instanceof Error?error.message:"Suppression could not be stored."},{status:400});}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const entryId=new URL(request.url).searchParams.get("entryId");if(!entryId)return NextResponse.json({error:"entryId is required"},{status:400});try{const context=await resolveWorkspace(id);const removed=await removeSuppressionPersistent(context.workspaceId,entryId);if(removed)await recordAuditPersistent({workspaceId:context.workspaceId,action:"suppression.removed",entityType:"suppression",entityId:entryId,metadata:{}});return NextResponse.json({removed,mode:context.mode},{status:removed?200:404});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});throw error;}}
