import type {Capability,EnrichmentInput,EnrichmentProvider,ProviderResult} from "./types";
import {providerJson} from "./http";
type ApolloResponse={people?:unknown[];person?:Record<string,unknown>;organization?:Record<string,unknown>;organizations?:unknown[];match_confidence?:string};
export class ApolloProvider implements EnrichmentProvider{
  readonly name="apollo";readonly capabilities:Capability[]=["company_search","company_enrichment","people_search","person_enrichment","email_find"];
  async estimateCost(input:EnrichmentInput){return input.capability==="people_search"||input.capability==="company_search"?0:1;}
  async canRun(input:EnrichmentInput){return Boolean(process.env.APOLLO_API_KEY)&&this.capabilities.includes(input.capability);}
  async enrich<T>(input:EnrichmentInput):Promise<ProviderResult<T>>{const key=process.env.APOLLO_API_KEY;if(!key)return {success:false,error:{code:"MISSING_CREDENTIAL",message:"Apollo is not configured.",retryable:false}};let url:string;let init:RequestInit={method:"POST",headers:{"content-type":"application/json","accept":"application/json","x-api-key":key,"cache-control":"no-cache"}};
    if(input.capability==="people_search"){if(!input.domain&&!input.companyName)return {success:false,error:{code:"MISSING_INPUT",message:"Company domain or name is required.",retryable:false}};url="https://api.apollo.io/api/v1/mixed_people/api_search";init.body=JSON.stringify({q_organization_domains_list:input.domain?[input.domain]:undefined,q_keywords:input.companyName,person_titles:input.targetRoles,include_similar_titles:true,page:1,per_page:10});}
    else if(input.capability==="company_search"){if(!input.companyName)return {success:false,error:{code:"MISSING_INPUT",message:"Company name is required.",retryable:false}};url="https://api.apollo.io/api/v1/mixed_companies/search";init.body=JSON.stringify({q_organization_name:input.companyName,page:1,per_page:10});}
    else if(input.capability==="company_enrichment"){if(!input.domain&&!input.companyName)return {success:false,error:{code:"MISSING_INPUT",message:"Company domain or name is required.",retryable:false}};const query=new URL("https://api.apollo.io/api/v1/organizations/enrich");if(input.domain)query.searchParams.set("domain",input.domain);if(input.companyName)query.searchParams.set("name",input.companyName);url=query.toString();init={method:"GET",headers:init.headers};}
    else if(input.capability==="person_enrichment"||input.capability==="email_find"){if(!input.email&&!input.personName)return {success:false,error:{code:"MISSING_INPUT",message:"Person name or email is required.",retryable:false}};const query=new URL("https://api.apollo.io/api/v1/people/match");if(input.email)query.searchParams.set("email",input.email);if(input.personName)query.searchParams.set("name",input.personName);if(input.domain)query.searchParams.set("domain",input.domain);query.searchParams.set("reveal_personal_emails","false");query.searchParams.set("reveal_phone_number","false");url=query.toString();}
    else return {success:false,error:{code:"UNSUPPORTED",message:"Phone reveal requires an approved webhook workflow.",retryable:false}};
    const result=await providerJson<ApolloResponse>(url,init);if(!result.success)return result as ProviderResult<T>;const confidence=result.data?.match_confidence==="high"?.95:result.data?.match_confidence==="medium"?.8:.72;return {success:true,data:result.data as T,confidence,costUnits:await this.estimateCost(input)};}
}
