import {desc,eq} from "drizzle-orm";
import {db} from "../../lib/db/client";
import {auditLogs,providerUsage} from "../../lib/db/schema";
import {isUuid} from "../../lib/workspace/context";
import {getOperations,recordAudit,recordUsage,type AuditEvent,type UsageEvent} from "../operations";

export async function recordUsagePersistent(event:Omit<UsageEvent,"createdAt">){recordUsage(event);if(!db||!isUuid(event.workspaceId))return;await db.insert(providerUsage).values({workspaceId:event.workspaceId,projectId:isUuid(event.projectId)?event.projectId:null,provider:event.provider,capability:event.capability,units:event.units,estimatedCost:String(event.estimatedCost),status:event.status});}
export async function recordAuditPersistent(event:Omit<AuditEvent,"createdAt">){recordAudit(event);if(!db||!isUuid(event.workspaceId)||!isUuid(event.entityId))return;await db.insert(auditLogs).values({workspaceId:event.workspaceId,action:event.action,entityType:event.entityType,entityId:event.entityId,metadataJson:event.metadata});}
export async function getOperationsPersistent(workspaceId:string){if(!db)return getOperations(workspaceId);const [usage,audit]=await Promise.all([db.select().from(providerUsage).where(eq(providerUsage.workspaceId,workspaceId)),db.select().from(auditLogs).where(eq(auditLogs.workspaceId,workspaceId)).orderBy(desc(auditLogs.createdAt)).limit(50)]);const providers=Object.values(usage.reduce<Record<string,{provider:string;calls:number;units:number;estimatedCost:number;successes:number}>>((all,event)=>{const item=all[event.provider]??={provider:event.provider,calls:0,units:0,estimatedCost:0,successes:0};item.calls++;item.units+=event.units;item.estimatedCost+=Number(event.estimatedCost??0);if(event.status==="success")item.successes++;return all;},{}));return {summary:{calls:usage.length,units:usage.reduce((sum,event)=>sum+event.units,0),estimatedCost:usage.reduce((sum,event)=>sum+Number(event.estimatedCost??0),0)},providers,audit:audit.map(event=>({workspaceId:event.workspaceId,action:event.action,entityType:event.entityType,entityId:event.entityId,metadata:event.metadataJson as Record<string,unknown>,createdAt:event.createdAt.toISOString()}))};}
