import {and,desc,eq} from "drizzle-orm";
import {db} from "../../lib/db/client";
import {suppressionList} from "../../lib/db/schema";
import {encryptionPersistenceReady} from "../../lib/security/encryption";
import {addSuppression,hashSuppression,isSuppressed,listSuppressions,maskSuppression,removeSuppression,type SuppressionType} from "../suppression";

function publicRow(row:typeof suppressionList.$inferSelect){return {id:row.id,workspaceId:row.workspaceId,type:row.type as SuppressionType,label:row.displayLabel,reason:row.reason,createdAt:row.createdAt.toISOString()};}
export async function listSuppressionsPersistent(workspaceId:string){if(!db)return listSuppressions(workspaceId);return (await db.select().from(suppressionList).where(eq(suppressionList.workspaceId,workspaceId)).orderBy(desc(suppressionList.createdAt))).map(publicRow);}
export async function addSuppressionPersistent(input:{workspaceId:string;type:SuppressionType;value:string;reason?:string|null}){if(!db)return addSuppression(input);if(!encryptionPersistenceReady())throw new Error("APP_ENCRYPTION_KEY is required before suppression hashes can be stored in PostgreSQL.");const normalizedHash=hashSuppression(input.type,input.value);const values={workspaceId:input.workspaceId,type:input.type,normalizedHash,displayLabel:maskSuppression(input.type,input.value),reason:input.reason??null};const inserted=await db.insert(suppressionList).values(values).onConflictDoNothing().returning();if(inserted[0])return publicRow(inserted[0]);const [existing]=await db.select().from(suppressionList).where(and(eq(suppressionList.workspaceId,input.workspaceId),eq(suppressionList.normalizedHash,normalizedHash))).limit(1);return publicRow(existing);}
export async function removeSuppressionPersistent(workspaceId:string,id:string){if(!db)return removeSuppression(workspaceId,id);return (await db.delete(suppressionList).where(and(eq(suppressionList.id,id),eq(suppressionList.workspaceId,workspaceId))).returning({id:suppressionList.id})).length>0;}
export async function isSuppressedPersistent(input:{workspaceId:string;type:SuppressionType;value:string}){if(!db)return isSuppressed(input);const [row]=await db.select({id:suppressionList.id}).from(suppressionList).where(and(eq(suppressionList.workspaceId,input.workspaceId),eq(suppressionList.normalizedHash,hashSuppression(input.type,input.value)))).limit(1);return Boolean(row);}
