import {NextResponse} from "next/server";
import {z} from "zod";
import {resolveWorkspace,WorkspaceAccessError} from "@/lib/workspace/context";
import {addSavedListPersistent,listSavedListsPersistent,removeSavedListPersistent} from "@/services/persistence/saved-lists";
import {recordAuditPersistent} from "@/services/persistence/operations";

const schema=z.object({name:z.string().trim().min(2).max(80),rule:z.string().trim().min(2).max(240)});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const context=await resolveWorkspace(id);return NextResponse.json({lists:await listSavedListsPersistent(context.workspaceId),mode:context.mode});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});throw error;}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid list",issues:parsed.error.issues},{status:400});try{const context=await resolveWorkspace(id);const list=await addSavedListPersistent({workspaceId:context.workspaceId,...parsed.data});await recordAuditPersistent({workspaceId:context.workspaceId,action:"list.created",entityType:"saved_list",entityId:list.id,metadata:{name:list.name}});return NextResponse.json({list,mode:context.mode},{status:201});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});throw error;}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const listId=new URL(request.url).searchParams.get("listId");if(!listId)return NextResponse.json({error:"listId is required"},{status:400});try{const context=await resolveWorkspace(id);const removed=await removeSavedListPersistent(context.workspaceId,listId);if(removed)await recordAuditPersistent({workspaceId:context.workspaceId,action:"list.removed",entityType:"saved_list",entityId:listId,metadata:{}});return NextResponse.json({removed,mode:context.mode},{status:removed?200:404});}catch(error){if(error instanceof WorkspaceAccessError)return NextResponse.json({error:error.message},{status:error.status});throw error;}}
