"use client";

import { useState } from "react";
import { Check, ChevronRight, Globe2, Pencil, ShieldCheck, Sparkles, X } from "lucide-react";
import type { BusinessAnalysis } from "@/lib/ai/schemas";

export function BusinessAnalysisReview({ analysis, projectName, onClose, onApprove }: { analysis: BusinessAnalysis; projectName: string; onClose: () => void; onApprove: (services: string[]) => Promise<void> }) {
  const [services, setServices] = useState(analysis.services);
  const [approved, setApproved] = useState(false);
  const [starting, setStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  return <div className="fixed inset-0 z-50 flex justify-end bg-[#142119]/30 backdrop-blur-[2px]" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="drawer-shadow animate-in flex h-full w-full max-w-[650px] flex-col bg-white">
    <header className="border-b border-[#e4e9e5] px-6 py-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#46705c]"><Sparkles size={13}/>AI business analysis <span className="rounded bg-[#edf4ef] px-2 py-0.5 text-[9px]">Mock mode</span></div><h2 className="font-display mt-2 text-xl font-extrabold">Review {projectName}</h2><p className="mt-1 text-xs text-[#758078]">Confirm the structured analysis before discovery starts.</p></div><button onClick={onClose} aria-label="Close analysis" className="rounded-lg p-2 hover:bg-[#f1f3f1]"><X size={18}/></button></div></header>
    <div className="scrollbar-thin flex-1 overflow-y-auto p-6"><div className="rounded-xl border border-[#dfe5e0] bg-[#fafbfa] p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-[#7a847d]">Business model</div><div className="mt-1.5 text-sm font-bold">{analysis.businessModel}</div><p className="mt-2 text-xs leading-5 text-[#5d6860]">{analysis.businessSummary}</p><div className="mt-3 flex items-center gap-1.5 text-[10px] font-semibold text-[#657068]"><Globe2 size={12}/>{analysis.geographies.join(", ")}</div></div>
      <section className="mt-6"><div className="flex items-center justify-between"><div><h3 className="font-display text-base font-bold">Services and personas</h3><p className="mt-1 text-xs text-[#7a837c]">Edit names now; deeper taxonomy editing comes next.</p></div><span className="text-[10px] font-bold text-[#718078]">{services.length} selected</span></div><div className="mt-3 space-y-2">{services.map((service,index)=><article key={`${service.name}-${index}`} className="rounded-xl border border-[#e0e5e1] p-4"><div className="flex items-start gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#e9f3ed] text-[#32644e]"><Check size={14}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><input aria-label={`Service ${index+1}`} value={service.name} onChange={(e)=>setServices(services.map((s,i)=>i===index?{...s,name:e.target.value}:s))} className="min-w-0 flex-1 border-0 bg-transparent text-sm font-bold outline-none"/><Pencil size={12} className="text-[#89918b]"/></div><div className="mt-1 text-[10px] text-[#7c857e]">{service.category}</div><div className="mt-2 flex flex-wrap gap-1.5">{service.buyerPersonas.slice(0,3).map(role=><span key={role} className="rounded-md bg-[#f2f4f2] px-2 py-1 text-[9px] font-semibold text-[#657068]">{role}</span>)}</div></div></div></article>)}</div></section>
      <section className="mt-6"><h3 className="font-display text-base font-bold">Recommended source order</h3><div className="mt-3 flex flex-wrap gap-2">{analysis.recommendedSources.map((source,i)=><span key={source} className="inline-flex items-center gap-1.5 rounded-lg border border-[#dfe5e0] px-2.5 py-2 text-[10px] font-semibold"><span className="grid h-4 w-4 place-items-center rounded-full bg-[#edf4ef] text-[8px] font-bold text-[#32644e]">{i+1}</span>{source.replaceAll("_"," ")}</span>)}</div></section>
      <section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-amber-800">Assumptions to review</div><ul className="mt-2 space-y-2">{analysis.assumptions.map(item=><li key={item} className="flex gap-2 text-xs leading-5 text-amber-900/80"><ChevronRight size={13} className="mt-1 shrink-0"/>{item}</li>)}</ul></section>
    </div>
    <footer className="border-t border-[#e4e9e5] bg-[#fbfcfb] px-6 py-4">{approved?<div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-bold text-[#2f674e]"><ShieldCheck size={16}/>Analysis approved; discovery completed in mock mode.</div><button onClick={onClose} className="rounded-lg bg-[#244f3e] px-4 py-2 text-xs font-bold text-white">View leads</button></div>:<div><div className="flex items-center justify-between"><button onClick={onClose} className="rounded-lg border border-[#dce2dd] px-4 py-2 text-xs font-semibold">Save draft</button><button disabled={starting} onClick={async()=>{setStarting(true);setError(null);try{await onApprove(services.map(service=>service.name));setApproved(true);}catch{setError("Discovery could not start. Please try again.");}finally{setStarting(false);}}} className="flex items-center gap-2 rounded-lg bg-[#244f3e] px-4 py-2 text-xs font-bold text-white disabled:opacity-60"><Sparkles size={13}/>{starting?"Discovering…":"Approve & start discovery"}</button></div>{error&&<p className="mt-2 text-right text-[10px] font-semibold text-red-700">{error}</p>}</div>}</footer>
  </section></div>;
}
