"use client";
import {FormEvent,useEffect,useState} from "react";
import {ListChecks,Plus,Trash2} from "lucide-react";
import {SectionShell} from "@/components/section-shell";
type SavedList={id:string;name:string;rule:string;count:number;system:boolean};
export default function ListsPage(){const [lists,setLists]=useState<SavedList[]>([]);const [name,setName]=useState("");const [rule,setRule]=useState("");const [notice,setNotice]=useState("");async function load(){const response=await fetch("/api/workspaces/demo/lists");const body=await response.json() as {lists:SavedList[]};setLists(body.lists);}useEffect(()=>{let active=true;fetch("/api/workspaces/demo/lists").then(response=>response.json() as Promise<{lists:SavedList[]}>).then(body=>{if(active)setLists(body.lists);});return()=>{active=false};},[]);
  async function submit(event:FormEvent){event.preventDefault();const response=await fetch("/api/workspaces/demo/lists",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,rule})});if(response.ok){setName("");setRule("");setNotice("Saved view created.");await load();}else setNotice("Enter a name and filter rule.");}
  async function remove(id:string){await fetch(`/api/workspaces/demo/lists?listId=${encodeURIComponent(id)}`,{method:"DELETE"});await load();}
  return <SectionShell title="Lists & saved views" description="Keep reusable lead groups for review, enrichment, and outreach preparation."><form onSubmit={submit} className="mb-5 grid gap-3 rounded-2xl border border-[#dde4de] bg-white p-5 shadow-sm md:grid-cols-[1fr_2fr_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="View name" className="h-11 rounded-lg border border-[#d8dfda] px-3"/><input required value={rule} onChange={e=>setRule(e.target.value)} placeholder="Rule, e.g. buyer · score 80+ · verified email" className="h-11 rounded-lg border border-[#d8dfda] px-3"/><button className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#244f3e] px-4 text-sm font-bold text-white"><Plus size={15}/>Save view</button>{notice&&<span className="text-sm text-[#35634f] md:col-span-3">{notice}</span>}</form><div className="overflow-hidden rounded-2xl border border-[#dde4de] bg-white">{lists.map(item=><article key={item.id} className="flex items-center gap-4 border-b border-[#edf0ed] px-5 py-5 last:border-0"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf4ef] text-[#35634f]"><ListChecks size={18}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-base font-bold">{item.name}</h2>{item.system&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">Default</span>}</div><p className="mt-1 text-sm text-[#6d7870]">{item.rule}</p></div><div className="text-right"><div className="font-display text-xl font-extrabold">{item.count}</div><div className="text-xs text-[#7a847d]">leads</div></div>{!item.system&&<button onClick={()=>void remove(item.id)} aria-label={`Delete ${item.name}`} className="rounded-lg p-2 text-[#8b5048] hover:bg-red-50"><Trash2 size={17}/></button>}</article>)}</div><p className="mt-4 text-xs text-[#77827a]">Saved views use session storage until Supabase is connected.</p></SectionShell>;}
