"use client";
import {FormEvent,useEffect,useState} from "react";
import {Plus,Save,Trash2} from "lucide-react";
import {SectionShell} from "@/components/section-shell";
type Config={leadThreshold:number;confidenceThreshold:number;retentionDays:number;mockMode:boolean;services:string[]};
const initial:Config={leadThreshold:70,confidenceThreshold:65,retentionDays:180,mockMode:true,services:[]};
export default function SettingsPage(){const [config,setConfig]=useState(initial);const [newService,setNewService]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{let active=true;fetch("/api/workspaces/demo/config").then(r=>r.json() as Promise<{config:Config}>).then(body=>{if(active)setConfig(body.config);});return()=>{active=false};},[]);
  async function save(event:FormEvent){event.preventDefault();setSaving(true);const response=await fetch("/api/workspaces/demo/config",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(config)});setNotice(response.ok?"Workspace settings saved.":"Settings could not be saved.");setSaving(false);}
  function addService(){const value=newService.trim();if(!value||config.services.some(item=>item.toLowerCase()===value.toLowerCase()))return;setConfig({...config,services:[...config.services,value]});setNewService("");}
  return <SectionShell title="Admin settings" description="Control lead quality, service taxonomy, retention, and safe execution defaults."><form onSubmit={save} className="space-y-5"><section className="rounded-2xl border border-[#dde4de] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Quality controls</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><label className="text-sm font-bold">Lead score threshold<input type="number" min="0" max="100" value={config.leadThreshold} onChange={e=>setConfig({...config,leadThreshold:Number(e.target.value)})} className="mt-2 h-11 w-full rounded-lg border border-[#d8dfda] px-3 text-base font-normal"/></label><label className="text-sm font-bold">Confidence threshold<input type="number" min="0" max="100" value={config.confidenceThreshold} onChange={e=>setConfig({...config,confidenceThreshold:Number(e.target.value)})} className="mt-2 h-11 w-full rounded-lg border border-[#d8dfda] px-3 text-base font-normal"/></label><label className="text-sm font-bold">Evidence retention (days)<input type="number" min="1" max="3650" value={config.retentionDays} onChange={e=>setConfig({...config,retentionDays:Number(e.target.value)})} className="mt-2 h-11 w-full rounded-lg border border-[#d8dfda] px-3 text-base font-normal"/></label></div><label className="mt-5 flex items-start gap-3 rounded-xl border border-[#dfe5e0] bg-[#f7f9f7] p-4"><input type="checkbox" checked={config.mockMode} onChange={e=>setConfig({...config,mockMode:e.target.checked})} className="mt-1"/><span><span className="block text-sm font-bold">Keep mock providers active</span><span className="mt-1 block text-sm leading-6 text-[#6d7870]">Prevents paid provider calls while testing. Turning this off does not enable providers without valid credentials.</span></span></label></section>
    <section className="rounded-2xl border border-[#dde4de] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Service taxonomy</h2><p className="mt-1 text-sm text-[#6d7870]">Categories are used by analysis, discovery, scoring, and decision-maker rules.</p><div className="mt-5 flex gap-2"><input value={newService} onChange={e=>setNewService(e.target.value)} placeholder="Add a service category" className="h-11 min-w-0 flex-1 rounded-lg border border-[#d8dfda] px-3"/><button type="button" onClick={addService} className="inline-flex items-center gap-2 rounded-lg border border-[#cad5ce] px-4 text-sm font-bold"><Plus size={15}/>Add</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{config.services.map(service=><div key={service} className="flex items-center justify-between rounded-lg border border-[#e0e5e1] px-3 py-3 text-sm font-semibold"><span>{service}</span><button type="button" aria-label={`Remove ${service}`} onClick={()=>setConfig({...config,services:config.services.filter(item=>item!==service)})} disabled={config.services.length===1} className="text-[#8b5048] disabled:opacity-30"><Trash2 size={15}/></button></div>)}</div></section>
    <div className="flex items-center gap-4"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#244f3e] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><Save size={15}/>{saving?"Saving…":"Save admin settings"}</button>{notice&&<span className="text-sm font-semibold text-[#35634f]">{notice}</span>}</div></form></SectionShell>;}
